server:
  session-timeout: 1800
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
  port: 8000
  uri-encoding: utf-8

spring:
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    encoding: UTF-8
    servlet:
      content-type: text/html
  resources:
    chain:
      enabled: false

logging:
  level:
    root: info
  org:
    thymeleaf: error

frc:
  host: https://dev.esandcloud.com
